apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "releasebot.fullname" . }}-payloads
data:
  payloads.json: |
    [
    {{- range $index, $payload := .Values.config.payloads }}
        {
            "name": "{{ $payload.name }}",
            "url": "{{ $payload.url }}",
            "payload": {{ toJson .payload }}
        }{{ if ne $index (sub (len $.Values.config.payloads) 1) }},{{end}}
    {{- end }}
    ]
